### ISSUE TITLE
Importing buttons and catalogs results in incorrect dialogs and entry points not referenced in export

### ISSUE THREAD

**Issue by aaronbradshaw** [rhtconsulting/cfme-rhconsulting-scripts#114]
On import we are seeing catalogs and buttons pointed at incorrect dialogs and entry points. We can start with the button case.

Button "Create Snapshot" pointed at an incorrect dialog 
Button "Request Ownership" pointed at an incorrect dialog 

As referenced below `dialog_label:` is not defined for these buttons.

Export is below:

Actions_Vm_.yaml
```yaml
---
:custom_buttons_sets:
- name: Actions|Vm|
  description: Actions
  set_type: CustomButtonSet
  read_only:
  mode:
  custom_buttons:
  - description: Add Additional Network
    applies_to_class: Vm
    applies_to_exp:
    options:
      :button_image: '2'
      :display: true
      :open_url: false
      :display_for: single
      :submit_how: one
    userid: admin
    wait_for_complete:
    name: Add Additional Network
    visibility:
      :roles:
      - _ALL_
    applies_to_id:
    resource_actions:
      action:
      ae_namespace: SYSTEM
      ae_class: PROCESS
      ae_instance: Request
      ae_message:
      ae_attributes:
        request: vmware_add_nic_to_vm
      dialog_label: Add Additional Network
  - description: Assign VM Ownership
    applies_to_class: Vm
    applies_to_exp:
    options:
      :button_image: 4
      :display: true
      :open_url: false
      :display_for: single
      :submit_how: one
    userid: admin
    wait_for_complete:
    name: Assign VM Ownership
    visibility:
      :roles:
      - _ALL_
    applies_to_id:
    resource_actions:
      action:
      ae_namespace: SYSTEM
      ae_class: PROCESS
      ae_instance: Request
      ae_message:
      ae_attributes:
        request: vmware_assign_owner
  - description: Create Snapshot
    applies_to_class: Vm
    applies_to_exp:
    options:
      :button_image: 6
      :display: true
      :open_url: false
      :display_for: single
      :submit_how: one
    userid: admin
    wait_for_complete:
    name: Create Snapshot
    visibility:
      :roles:
      - _ALL_
    applies_to_id:
    resource_actions:
      action:
      ae_namespace: SYSTEM
      ae_class: PROCESS
      ae_instance: Request
      ae_message:
      ae_attributes:
        request: create_custom_snapshot
  - description: Remove Snapshots if over 1 snapshot
    applies_to_class: Vm
    applies_to_exp:
    options:
      :button_image: 7
      :display: true
      :open_url: false
      :display_for: single
      :submit_how: one
    userid: admin
    wait_for_complete:
    name: Remove Snapshots
    visibility:
      :roles:
      - _ALL_
    applies_to_id:
    resource_actions:
      action:
      ae_namespace: SYSTEM
      ae_class: PROCESS
      ae_instance: Request
      ae_message:
      ae_attributes:
        request: vmware_remove_snapshots
  - description: Request Ownership of VM
    applies_to_class: Vm
    applies_to_exp:
    options:
      :button_image: 14
      :display: true
      :open_url: false
      :display_for: single
      :submit_how: one
    userid: admin
    wait_for_complete:
    name: Request Ownership
    visibility:
      :roles:
      - _ALL_
    applies_to_id:
    resource_actions:
      action:
      ae_namespace: SYSTEM
      ae_class: PROCESS
      ae_instance: Request
      ae_message:
      ae_attributes:
        request: vm_request_ownership
  - description: Revert to Previous Snapshot
    applies_to_class: Vm
    applies_to_exp:
    options:
      :button_image: 11
      :display: true
      :open_url: false
      :display_for: single
      :submit_how: one
    userid: admin
    wait_for_complete:
    name: Revert to Previous Snapshot
    visibility:
      :roles:
      - _ALL_
    applies_to_id:
    resource_actions:
      action:
      ae_namespace: SYSTEM
      ae_class: PROCESS
      ae_instance: Request
      ae_message:
      ae_attributes:
        request: vmware_revert_snapshot
  - description: Change Network
    applies_to_class: Vm
    applies_to_exp:
    options:
      :button_image: '3'
      :display: true
      :open_url: false
      :display_for: single
      :submit_how: one
    userid: admin
    wait_for_complete:
    name: Change Network
    visibility:
      :roles:
      - _ALL_
    applies_to_id:
    resource_actions:
      action:
      ae_namespace: SYSTEM
      ae_class: PROCESS
      ae_instance: Request
      ae_message:
      ae_attributes:
        request: vmware_change_vm_network
      dialog_label: Change Network
  - description: Set VM Credentials
    applies_to_class: Vm
    applies_to_exp:
    options:
      :button_image: '8'
      :display: true
      :open_url: false
      :display_for: single
      :submit_how: one
    userid: admin
    wait_for_complete:
    name: Set VM Credentials
    visibility:
      :roles:
      - _ALL_
    applies_to_id:
    resource_actions:
      action:
      ae_namespace: SYSTEM
      ae_class: PROCESS
      ae_instance: Request
      ae_message:
      ae_attributes:
        request: set_vm_credentials
      dialog_label: Set VM Credentials
  set_data:
    :button_order:
    - Add Additional Network
    - Assign VM Ownership
    - Create Snapshot
    - Change Network
    - Remove Snapshots
    - Request Ownership
    - Revert to Previous Snapshot
    - Set VM Credentials
    :button_image: 1
    :display: true
    :group_index: 1
```
